# CMake generated Testfile for 
# Source directory: F:/mcs2/openMVS
# Build directory: F:/mcs2/openMVS
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(UnitTests "" "0")
  set_tests_properties(UnitTests PROPERTIES  _BACKTRACE_TRIPLES "F:/mcs2/openMVS/CMakeLists.txt;271;ADD_TEST;F:/mcs2/openMVS/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(UnitTests "" "0")
  set_tests_properties(UnitTests PROPERTIES  _BACKTRACE_TRIPLES "F:/mcs2/openMVS/CMakeLists.txt;271;ADD_TEST;F:/mcs2/openMVS/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(UnitTests "" "0")
  set_tests_properties(UnitTests PROPERTIES  _BACKTRACE_TRIPLES "F:/mcs2/openMVS/CMakeLists.txt;271;ADD_TEST;F:/mcs2/openMVS/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(UnitTests "" "0")
  set_tests_properties(UnitTests PROPERTIES  _BACKTRACE_TRIPLES "F:/mcs2/openMVS/CMakeLists.txt;271;ADD_TEST;F:/mcs2/openMVS/CMakeLists.txt;0;")
else()
  add_test(UnitTests NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(PipelineTest "" "1")
  set_tests_properties(PipelineTest PROPERTIES  _BACKTRACE_TRIPLES "F:/mcs2/openMVS/CMakeLists.txt;272;ADD_TEST;F:/mcs2/openMVS/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(PipelineTest "" "1")
  set_tests_properties(PipelineTest PROPERTIES  _BACKTRACE_TRIPLES "F:/mcs2/openMVS/CMakeLists.txt;272;ADD_TEST;F:/mcs2/openMVS/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(PipelineTest "" "1")
  set_tests_properties(PipelineTest PROPERTIES  _BACKTRACE_TRIPLES "F:/mcs2/openMVS/CMakeLists.txt;272;ADD_TEST;F:/mcs2/openMVS/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(PipelineTest "" "1")
  set_tests_properties(PipelineTest PROPERTIES  _BACKTRACE_TRIPLES "F:/mcs2/openMVS/CMakeLists.txt;272;ADD_TEST;F:/mcs2/openMVS/CMakeLists.txt;0;")
else()
  add_test(PipelineTest NOT_AVAILABLE)
endif()
subdirs("libs")
subdirs("apps")
subdirs("docs")
